### ISSUE TITLE
创建班级时班级logo总是提示“不支持的图片格式”

### ISSUE THREAD

**Issue by ghost** [cnblogs/edu#10]
在创建班级或编辑班级时，想要修改logo，但上传logo后一直提示格式不正确。尝试了jpg、png和gif格式，均如图片所示，弹出”不支持的图片格式“。
系统环境：macOS 10.15.3,  Safari 13.0.5 (15608.5.11)
![251582125665_ pic_hd](https://user-images.githubusercontent.com/41187791/74850914-7bb59c00-5375-11ea-8d9d-86cd17115fee.jpg)

**Comment by cnblogs-team** [comment]
您好，该问题已修复，抱歉，给您带来麻烦了。

**Comment by ghost** [comment]
上传logo已成功，感谢
