### ISSUE TITLE
修改部分文字表达

### ISSUE THREAD

**Issue by jihuayu** [cnblogs/edu#8]
![1](https://user-images.githubusercontent.com/32858525/73130508-74c89180-4034-11ea-867b-5e2352e89a0c.png)
如上图，建议把`提交博文`修改成`分享博文`，部分同学认为此处是提交作业入口。

![QQ截图20200126120906](https://user-images.githubusercontent.com/32858525/73130521-aa6d7a80-4034-11ea-808d-8a94bb5b3220.png)
如上图，建议把`已完成`修改成`已截止`，部分同学认为出现已完成代表已经提交了作业。

**Comment by cnblogs-team** [comment]
您好，谢谢您的建议，我们会尽快进行改进。

**Comment by cnblogs-team** [comment]
您好，感谢您的建议，已修改。
